### ISSUE TITLE
链接数据库错误

### ISSUE THREAD

**Issue by huang303513** [yyss8/Scms#4]
楼主，我服务器mongdb的版本是3.4。你能不能升级一下数据库，我这里不管如何改，都错在services文件夹下面的const collection = db.collection(dbName); 这句话上面。

**Comment by yyss8** [comment]
你好, huang303513 
不好意思, 最近工作方面都在用mysql, 好久没用mongodb了 所以在之前电脑上重新搭环境折腾了一阵子
mongdob的3.4版本已经发布有一阵子了  所以版本上应该是没问题的 最新的好像是3.6?  我电脑上装的也是3.4 
我也重新在我电脑上运行了这个博客系统 貌似没有什么问题

所以我猜想是不是你没有在你的数据库中导入dump文件夹 里的数据, 所以导致程序无法在你的数据库中找到这个表(collection)

如果是的话你可以用例如studio 3t for mongodb这类工具将我上传的dump文件夹下的数据导入到你的数据库中, 然后在config文件夹里的db.config.js中改动你相应的数据库连接信息

还有就是在目录component/header/ 下的headersetting.vue文件 有一个按钮的tag我拼错了  结尾应该是/button 但是被我拼成/buttuon  所以webpack在compile的时候可能会报错  你可以试着改下

不过这些都只是我的猜想,  如果还是有类似的问题请再回复

3q
